Repository pulsate-dev/pulsate, pull requests merged in 2023-12, with the labels that each got.

#100 feat: API/バリデータの定義
  deno.jsonc
  deno.lock
  main.ts
  pkg/accounts/adaptor/validator/schema.ts
  pkg/accounts/mod.ts
  pkg/accounts/router.ts
Labels: T: feature, Antenna (v0 & v1), P: high

#104 fix: remove unused microservice files
  deployment.yaml
  kustomization.yaml
  service.yaml
  staging/.terraform.lock.hcl
  staging/main.tf
  staging/outputs.tf
  staging/terraform.tfvars
  staging/variables.tf
Labels: T: improvement

#105 fix(bug): wrong format verify token
  deno.jsonc
  deno.lock
  pkg/accounts/service/tokenVerify.test.ts
  pkg/accounts/service/tokenVerify.ts
Labels: T: bug (confirmed), Antenna (v0 & v1)

#106 chore: change function name to camelCase
  pkg/accounts/service/editAccount.ts
  pkg/accounts/service/etagGenerateVerify.test.ts
  pkg/accounts/service/etagGenerateVerify.ts
Labels: T: improvement

#110 fix: replace single quote to full-width apostrophe
  pkg/accounts/model/account.test.ts
Labels: P: high

#107 feat: resend account verify code
  pkg/accounts/service/resendToken.test.ts
  pkg/accounts/service/resendToken.ts
Labels: T: feature, Antenna (v0 & v1), P: high

#114 feat: Account name validation with template literal
  pkg/accounts/model/account.test.ts
  pkg/accounts/model/account.ts
  pkg/accounts/service/editAccount.test.ts
  pkg/accounts/service/etagGenerateVerify.test.ts
  pkg/accounts/service/freeze.test.ts
  pkg/accounts/service/register.test.ts
  pkg/accounts/service/register.ts
  pkg/accounts/service/silence.test.ts
Labels: Antenna (v0 & v1), P: high
