Repository pulsate-dev/pulsate, pull requests merged in 2023-11, with the labels that each got.

#58 feat: Add accounts package
  deno.lock
  main.ts
  pkg/accounts/README.md
  pkg/accounts/adaptor/.gitkeep
  pkg/accounts/mod.ts
  pkg/accounts/model/.gitkeep
  pkg/accounts/service/.gitkeep
Labels: T: feature

#59 feat: generate SnowflakeID
  deno.lock
  pkg/id/README.md
  pkg/id/mod.test.ts
  pkg/id/mod.ts
  pkg/id/type.ts
Labels: T: feature, Antenna (v0 & v1), P: high

#62 chore: renovate のセットアップ
  .github/renovate.json
Labels: T: renovate

#71 docs: Added about pulsate project to README.md
  README.md
Labels: T: docs

#60 feat: Account domain model
  deno.jsonc
  deno.lock
  pkg/accounts/model/account.errors.ts
  pkg/accounts/model/account.test.ts
  pkg/accounts/model/account.ts
Labels: T: feature, Antenna (v0 & v1), P: high

#79 feat: アカウント登録の実装
  deno.jsonc
  deno.lock
  pkg/accounts/adaptor/repository/dummy.ts
  pkg/accounts/adaptor/repository/mariadb.ts
  pkg/accounts/model/account.test.ts
  pkg/accounts/model/repository.ts
  pkg/accounts/service/register_service.test.ts
  pkg/accounts/service/register_service.ts
  pkg/accounts/service/send_notification_service.ts
  pkg/accounts/service/token_generator.test.ts
  pkg/accounts/service/token_generator.ts
  pkg/accounts/service/token_verify_service.test.ts
  pkg/accounts/service/token_verify_service.ts
  pkg/password/mod.test.ts
  pkg/password/mod.ts
  resources/db/20231110191158_add_account_verify_token.sql
  services/hello/main.ts
Labels: T: feature, Antenna (v0 & v1), P: high

#80 fix: repository method naming
  pkg/accounts/adaptor/repository/dummy.ts
  pkg/accounts/model/repository.ts
  pkg/accounts/service/register_service.ts
  pkg/accounts/service/token_verify_service.ts
Labels: Antenna (v0 & v1), T: improvement

#87 test: add vscode debugger configuration `launch.json`
  .vscode/launch.json
Labels: Antenna (v0 & v1)

#55 docs: 行動規範を Org の .github リポジトリに統一
  .github/CODE_OF_CONDUCT_JA.md
  .github/PULL_REQUEST_TEMPLATE.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: T: docs

#96 feat: implements `EditAccountService`
  pkg/accounts/model/account.test.ts
  pkg/accounts/model/account.ts
  pkg/accounts/service/edit_account_service.test.ts
  pkg/accounts/service/edit_account_service.ts
Labels: T: feature
