Repository pulsate-dev/pulsate, pull requests merged in 2024-07, with the labels that each got.

#553 fix: flaky tests, add InMemoryTimelineRepository tests
  pkg/timeline/adaptor/repository/dummy.test.ts
  pkg/timeline/adaptor/repository/dummy.ts
  pkg/timeline/service/account.test.ts
Labels: T: bug (confirmed), P: high

#554 docs: Update repository documents
  .github/PULL_REQUEST_TEMPLATE.md
  AUTHORS.md
  CONTRIBUTING.md
  LICENSE
  README.md
  SECURITY.md
Labels: T: docs, requires core approval

#567 feat: define List model
  pkg/timeline/model/list.test.ts
  pkg/timeline/model/list.ts
Labels: T: feature

#574 chore: Replace ESLint and Prettier to Biome
  .github/renovate.json
  .github/workflows/build.yaml
  .ls-lint.yml
  .prettierrc
  .vscode/extensions.json
  .vscode/settings.json
  README.md
  biome.jsonc
  eslint.config.js
  lefthook.yml
  package.json
  pkg/accounts/adaptor/controller/account.ts
  pkg/accounts/adaptor/repository/dummy.ts
  pkg/accounts/adaptor/repository/prisma.ts
  pkg/accounts/mod.ts
  pkg/accounts/model/inactiveAccount.test.ts
  pkg/accounts/model/inactiveAccount.ts
  pkg/accounts/model/repository.ts
  pkg/accounts/service/authenticate.test.ts
  pkg/accounts/service/authenticate.ts
  pkg/accounts/service/authenticationTokenService.test.ts
  pkg/accounts/service/edit.ts
  pkg/accounts/service/fetch.ts
  pkg/accounts/service/follow.ts
  pkg/accounts/service/freeze.ts
  pkg/accounts/service/register.test.ts
  pkg/accounts/service/resendToken.ts
  pkg/accounts/service/silence.ts
  pkg/accounts/service/unfollow.ts
  pkg/accounts/service/verifyToken.ts
  pkg/adaptors/authenticateMiddleware.ts
  pkg/drive/adaptor/controller/drive.ts
  pkg/drive/adaptor/repository/dummy.ts
  pkg/drive/adaptor/repository/prisma.ts
  pkg/drive/service/upload.test.ts
  pkg/intermodule/account.ts
  pkg/intermodule/timeline.ts
  pkg/notes/adaptor/controller/note.ts
  pkg/notes/adaptor/repository/dummy.ts
  pkg/notes/adaptor/repository/prisma.ts
  pkg/notes/mod.ts
  pkg/notes/model/bookmark.test.ts
  pkg/notes/model/repository.ts
  pkg/notes/service/fetch.ts
  pkg/password/mod.ts
  pkg/timeline/adaptor/controller/timeline.ts
  pkg/timeline/adaptor/repository/dummy.test.ts
  pkg/timeline/adaptor/repository/dummyCache.ts
  pkg/timeline/adaptor/repository/valkeyCache.ts
  pkg/timeline/service/noteVisibility.test.ts
  pkg/timeline/service/noteVisibility.ts
  pnpm-lock.yaml
  scripts/apidoc.ts
  scripts/build.js
  tsconfig.json
Labels: T: development

#577 feat: impl CreateList API Endpoint
  main.ts
  pkg/timeline/adaptor/controller/timeline.ts
  pkg/timeline/adaptor/repository/dummy.test.ts
  pkg/timeline/adaptor/repository/dummy.ts
  pkg/timeline/adaptor/repository/prisma.ts
  pkg/timeline/adaptor/validator/timeline.ts
  pkg/timeline/mod.ts
  pkg/timeline/model/repository.ts
  pkg/timeline/router.ts
  pkg/timeline/service/createList.test.ts
  pkg/timeline/service/createList.ts
  resources/schema.json
Labels: T: feature, Antenna (v0 & v1), P: high

#584 fix: APIで空オブジェクトを返すのをやめた
  pkg/accounts/adaptor/validator/schema.ts
  pkg/accounts/router.ts
  resources/schema.json
Labels: T: improvement

#585 refactor: intermodule, use direct function calls
  pkg/intermodule/account.ts
  pkg/intermodule/timeline.ts
  pkg/notes/adaptor/controller/note.ts
  pkg/notes/mod.ts
  pkg/notes/service/fetch.test.ts
  pkg/notes/service/fetch.ts
  pkg/timeline/adaptor/controller/timeline.ts
  pkg/timeline/mod.ts
  pkg/timeline/service/account.test.ts
  pkg/timeline/service/noteVisibility.test.ts
  pkg/timeline/service/noteVisibility.ts
  pkg/timeline/service/push.test.ts
  pkg/timeline/service/push.ts
Labels: T: improvement, T: refactoring

#588 feat: アカウントの複数一括取得の実装
  pkg/accounts/adaptor/repository/dummy.test.ts
  pkg/accounts/adaptor/repository/dummy.ts
  pkg/accounts/adaptor/repository/prisma.ts
  pkg/accounts/model/repository.ts
  pkg/accounts/service/fetch.test.ts
  pkg/accounts/service/fetch.ts
  pkg/intermodule/account.ts
  pnpm-lock.yaml
Labels: T: feature

#591 feat: impl fetch list members
  pkg/accounts/testData/testData.ts
  pkg/timeline/adaptor/controller/timeline.ts
  pkg/timeline/adaptor/validator/timeline.ts
  pkg/timeline/mod.ts
  pkg/timeline/router.ts
  pkg/timeline/service/fetchMember.test.ts
  pkg/timeline/service/fetchMember.ts
  pkg/timeline/service/noteVisibility.test.ts
  pkg/timeline/service/push.test.ts
  pkg/timeline/testData/testData.ts
  resources/schema.json
Labels: T: feature
