Repository pulsate-dev/pulsate, pull requests merged in 2024-02, with the labels that each got.

#116 feat(test): Porting all tests to vitest
  .gitignore
  .hooks/pre-commit
  deno.jsonc
  deno.lock
  main.ts
  package.json
  pkg/accounts/adaptor/repository/dummy.ts
  pkg/accounts/adaptor/validator/schema.ts
  pkg/accounts/mod.ts
  pkg/accounts/model/account.test.ts
  pkg/accounts/model/account.ts
  pkg/accounts/model/repository.ts
  pkg/accounts/router.ts
  pkg/accounts/service/.gitkeep
  pkg/accounts/service/editAccount.test.ts
  pkg/accounts/service/editAccount.ts
  pkg/accounts/service/etagGenerateVerify.test.ts
  pkg/accounts/service/etagGenerateVerify.ts
  pkg/accounts/service/freeze.test.ts
  pkg/accounts/service/freeze.ts
  pkg/accounts/service/register.test.ts
  pkg/accounts/service/register.ts
  pkg/accounts/service/resendToken.test.ts
  pkg/accounts/service/resendToken.ts
  pkg/accounts/service/sendNotification.ts
  pkg/accounts/service/silence.test.ts
  pkg/accounts/service/silence.ts
  pkg/accounts/service/tokenGenerator.test.ts
  pkg/accounts/service/tokenGenerator.ts
  pkg/accounts/service/tokenVerify.test.ts
  pkg/accounts/service/tokenVerify.ts
  pkg/id/mod.test.ts
  pkg/id/mod.ts
  pkg/password/mod.test.ts
  pkg/password/mod.ts
  pnpm-lock.yaml
  tsconfig.json
  vite.config.ts
Labels: P: high, T: improvement

#119 chore: Replace missing Node.js settings
  .github/CONTRIBUTING_JA.md
  .vscode/extensions.json
  .vscode/settings.json
  CONTRIBUTING.md
  README.md
Labels: Antenna (v0 & v1), P: high, T: development

#120 chore: setup commit hook
  lefthook.yml
  package.json
  pnpm-lock.yaml
Labels: Antenna (v0 & v1), P: high, T: development

#113 feat: add `FetchAccountService`
  pkg/accounts/service/fetchAccount.test.ts
  pkg/accounts/service/fetchAccount.ts
Labels: T: feature, Antenna (v0 & v1), P: high

#121 test: replace `RegisterService` to `InMemoryAccountRepository`
  pkg/accounts/service/editAccount.test.ts
  pkg/accounts/service/etagGenerateVerify.test.ts
  pkg/accounts/service/fetchAccount.test.ts
  pkg/accounts/service/freeze.test.ts
  pkg/accounts/service/silence.test.ts
Labels: Antenna (v0 & v1), P: high, T: improvement

#122 chore: specify Node.js engines and pnpm version
  .github/CONTRIBUTING_JA.md
  .github/workflows/node.yaml
  .tool-versions
  CONTRIBUTING.md
  package.json
Labels: Antenna (v0 & v1), T: development

#118 feat: impl `AuthenticationService`
  pkg/accounts/model/account.ts
  pkg/accounts/service/authenticate.test.ts
  pkg/accounts/service/authenticate.ts
  pkg/accounts/service/tokenGenerator.test.ts
  pkg/accounts/service/tokenGenerator.ts
  pkg/id/mod.ts
  pkg/time/mod.ts
Labels: T: feature, Antenna (v0 & v1), P: high

#126 ci: remove `staging-apply` ci
  .github/actions/list_dockerfile/action.yml
  .github/workflows/staging-apply.yaml
Labels: Antenna (v0 & v1), P: high

#125 feat(repository): postgres repository implementation
  .gitignore
  package.json
  pkg/accounts/adaptor/repository/mariadb.ts
  pkg/accounts/adaptor/repository/prisma.ts
  pkg/accounts/service/authenticate.test.ts
  pnpm-lock.yaml
  prisma/migrations/20240210015736_init/migration.sql
  prisma/migrations/20240210033025_add_missing_property_to_account/migration.sql
  prisma/migrations/20240210122847_update_some_missing_columns/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  resources/docker/compose.yaml
Labels: T: feature, Antenna (v0 & v1), P: high

#129 feat: Coverage report with Codecov
  .github/workflows/node.yaml
  .gitignore
  package.json
  pnpm-lock.yaml
  vite.config.ts
Labels: T: improvement

#132 docs: some corrections in `README.md`.
  README.md
Labels: T: docs, Antenna (v0 & v1), P: high

#137 feat: Service method for specifying accounts by name.
  pkg/accounts/service/accountVerifyToken.test.ts
  pkg/accounts/service/accountVerifyToken.ts
  pkg/accounts/service/follow.test.ts
  pkg/accounts/service/follow.ts
  pkg/accounts/service/freeze.ts
  pkg/accounts/service/register.test.ts
  pkg/accounts/service/register.ts
  pkg/accounts/service/resendToken.test.ts
  pkg/accounts/service/resendToken.ts
  pkg/accounts/service/silence.ts
  pkg/accounts/service/unfollow.test.ts
  pkg/accounts/service/unfollow.ts
Labels: P: high, T: improvement

#139 feat: define note model
  pkg/notes/model/note.test.ts
  pkg/notes/model/note.ts
Labels: T: feature

#140 fix: enable no-floating-promises
  eslint.config.js
  pkg/accounts/service/editAccount.test.ts
  pkg/accounts/service/etagGenerateVerify.test.ts
  pkg/accounts/service/fetchAccount.test.ts
  pkg/accounts/service/follow.test.ts
  pkg/accounts/service/freeze.test.ts
  pkg/accounts/service/silence.test.ts
  pkg/accounts/service/unfollow.test.ts
Labels: T: development

#141 feat: define and implement AccountRepository
  pkg/accounts/adaptor/repository/dummy.ts
  pkg/notes/adaptor/repository/dummy.ts
  pkg/notes/model/note.test.ts
  pkg/notes/model/note.ts
  pkg/notes/model/repository.ts
Labels: T: feature
