Repository pulsate-dev/pulsate, pull requests merged in 2024-06, with the labels that each got.

#409 chore: remove out-of-date renovate config
  .github/renovate.json
  .github/workflows/auto-assign-pr.yaml
Labels: T: development

#412 feat: use prisma repository when sets NODE_ENV=production
  pkg/accounts/adaptor/repository/prisma.ts
  pkg/accounts/mod.ts
  pkg/adaptors/prisma.ts
Labels: T: improvement

#418 feat: use prisma generated type at PrismaAccontRepository
  pkg/accounts/adaptor/repository/prisma.ts
Labels: T: improvement

#419 fix: ETag生成の実装ミスを修正
  pkg/accounts/service/etagService.ts
Labels: T: bug (confirmed), P: high

#428 feat: Account Timeline
  pkg/accounts/adaptor/controller/account.ts
  pkg/accounts/adaptor/validator/schema.ts
  pkg/accounts/mod.ts
  pkg/accounts/router.ts
  pkg/intermodule/account.ts
  pkg/timeline/adaptor/controller/timeline.ts
  pkg/timeline/adaptor/repository/dummy.ts
  pkg/timeline/adaptor/repository/prisma.ts
  pkg/timeline/adaptor/validator/timeline.ts
  pkg/timeline/mod.ts
  pkg/timeline/model/repository.ts
  pkg/timeline/router.ts
  pkg/timeline/service/account.test.ts
  pkg/timeline/service/account.ts
  pkg/timeline/service/noteVisibility.test.ts
  pkg/timeline/service/noteVisibility.ts
Labels: T: feature, Antenna (v0 & v1), P: high

#436 fix: Replace ID<NoteID> to ID<Note>
  pkg/notes/adaptor/controller/bookmark.ts
  pkg/notes/adaptor/controller/note.ts
  pkg/notes/adaptor/repository/dummy.ts
  pkg/notes/adaptor/repository/prisma.ts
  pkg/notes/model/bookmark.test.ts
  pkg/notes/model/bookmark.ts
  pkg/notes/model/note.test.ts
  pkg/notes/model/note.ts
  pkg/notes/model/repository.ts
  pkg/notes/service/create.ts
  pkg/notes/service/createBookmark.test.ts
  pkg/notes/service/createBookmark.ts
  pkg/notes/service/deleteBookmark.test.ts
  pkg/notes/service/deleteBookmark.ts
  pkg/notes/service/fetch.test.ts
  pkg/notes/service/fetch.ts
  pkg/notes/service/fetchBookmark.test.ts
  pkg/notes/service/fetchBookmark.ts
  pkg/notes/service/renote.test.ts
  pkg/notes/service/renote.ts
  pkg/timeline/adaptor/controller/timeline.ts
  pkg/timeline/adaptor/repository/prisma.ts
  pkg/timeline/model/repository.ts
  pkg/timeline/service/account.test.ts
  pkg/timeline/service/noteVisibility.test.ts
Labels: T: improvement

#439 feat: Require authorization token at handlers
  pkg/accounts/mod.ts
  pkg/accounts/service/authenticationTokenService.ts
  pkg/adaptors/authenticateMiddleware.ts
  pkg/notes/mod.ts
Labels: T: feature, T: improvement

#440 feat: impl home timeline
  package.json
  pkg/intermodule/timeline.ts
  pkg/timeline/adaptor/repository/dummy.ts
  pkg/timeline/adaptor/repository/dummyCache.ts
  pkg/timeline/adaptor/repository/prisma.ts
  pkg/timeline/adaptor/repository/valkeyCache.ts
  pkg/timeline/mod.ts
  pkg/timeline/model/repository.ts
  pkg/timeline/router.ts
  pkg/timeline/service/home.test.ts
  pkg/timeline/service/home.ts
  pkg/timeline/service/noteVisibility.test.ts
  pkg/timeline/service/noteVisibility.ts
  pkg/timeline/service/push.test.ts
  pkg/timeline/service/push.ts
  pkg/timeline/testData/testData.ts
  pnpm-lock.yaml
  resources/docker/compose.yaml
Labels: T: feature, P: high, T: improvement

#460 feat: Replace `ID<MediumID>` to `MediumID`
  pkg/drive/adaptor/repository/dummy.ts
  pkg/drive/adaptor/repository/prisma.ts
  pkg/drive/model/medium.ts
  pkg/drive/model/repository.ts
  pkg/drive/service/upload.test.ts
  pkg/drive/service/upload.ts
Labels: T: improvement

#464 feat: impl get account uploaded media handler,services
  main.ts
  pkg/drive/adaptor/controller/drive.ts
  pkg/drive/adaptor/repository/dummy.ts
  pkg/drive/adaptor/validator/schema.ts
  pkg/drive/mod.ts
  pkg/drive/router.ts
  pkg/drive/service/fetch.test.ts
  pkg/drive/service/fetch.ts
  pkg/drive/service/upload.test.ts
  resources/schema.json
Labels: T: feature
