Repository pulsate-dev/pulsate, pull requests merged in 2024-03, with the labels that each got.

#217 feat: impl FetchNoteService and Controller, Handler
  pkg/accounts/adaptor/controller/account.ts
  pkg/accounts/adaptor/repository/dummy.ts
  pkg/accounts/adaptor/repository/prisma.ts
  pkg/accounts/model/account.ts
  pkg/accounts/model/repository.ts
  pkg/accounts/service/fetchAccount.test.ts
  pkg/accounts/service/fetchAccount.ts
  pkg/intermodule/account.ts
  pkg/notes/adaptor/controller/note.ts
  pkg/notes/adaptor/validator/schema.ts
  pkg/notes/mod.ts
  pkg/notes/router.ts
  pkg/notes/service/fetch.test.ts
  pkg/notes/service/fetch.ts
Labels: T: feature, P: high

#220 docs: fix security policy file path
  .github/CONTRIBUTING_JA.md
Labels: T: docs

#222 chore: fix `clean` script
  package.json
Labels: T: hotfix, T: development

#221 chore: Add generate Prisma Client script
  .github/CONTRIBUTING_JA.md
  CONTRIBUTING.md
  package.json
Labels: T: development

#224 test: Reset account repository with `afterEach`
  pkg/accounts/service/resendToken.test.ts
  pkg/notes/service/fetch.test.ts
Labels: T: improvement

#231 chore: fix eslint configuration
  eslint.config.js
  package.json
  pnpm-lock.yaml
Labels: T: development

#234 ci: Add a step for type testing
  .github/workflows/ci.yaml
  package.json
Labels: T: development

#235 docs: fix ci badge
  README.md
Labels: T: development

#236 test: restrict coverage measure to the `pkg/` dir only
  vite.config.ts
Labels: T: improvement

#237 chore: ls-lint to detect casing of filenames
  .github/workflows/ci.yaml
  .ls-lint.yml
  lefthook.yml
  package.json
  pnpm-lock.yaml
Labels: T: development

#238 docs: allow filename casing `lowercase`
  .github/CONTRIBUTING_JA.md
  CONTRIBUTING.md
Labels: T: docs

#240 ci: bump `pnpm/action-setup` v2 to v3
  .github/workflows/ci.yaml
Labels: T: development

#243 docs: Remove remaining Deno content from Contributing Guide
  .github/CONTRIBUTING_JA.md
  CONTRIBUTING.md
Labels: T: docs

#249 chore: remove outdated api docs
  docs/api.yaml
Labels: T: docs

#245 feat: add `FetchAccountFollowService`
  pkg/accounts/service/fetchAccountFollow.test.ts
  pkg/accounts/service/fetchAccountFollow.ts
Labels: T: feature
