Repository pulsate-dev/pulsate, pull requests merged in 2024-04, with the labels that each got.

#244 feat: add zod schema of domain primitives
  pkg/accounts/model/account.test.ts
  pkg/accounts/model/account.ts
  pkg/id/mod.test.ts
  pkg/id/mod.ts
Labels: T: feature

#264 feat: リノートの実装
  pkg/notes/adaptor/controller/note.ts
  pkg/notes/adaptor/validator/schema.ts
  pkg/notes/mod.ts
  pkg/notes/model/note.test.ts
  pkg/notes/model/note.ts
  pkg/notes/router.ts
  pkg/notes/service/create.ts
  pkg/notes/service/fetch.test.ts
  pkg/notes/service/renote.test.ts
  pkg/notes/service/renote.ts
Labels: T: feature

#283 feat: add `Bookmark` model
  pkg/notes/model/bookmark.test.ts
  pkg/notes/model/bookmark.ts
Labels: T: feature

#308 docs: remove japanese version
  .github/CODEOWNERS
  .github/CONTRIBUTING_JA.md
  .github/SECURITY_JA.md
  CONTRIBUTING.md
  SECURITY.md
Labels: requires core approval

#315 ci: fix pnpm version issue
  .github/workflows/ci.yaml
Labels: T: hotfix, T: development
